development:
  adapter: postgresql
  database: database_dev
  username: ManishKukreja
  password: unix11
  template: template0
  pool: 5
  timeout: 5000
  port: 5432
  
test:
  adapter: postgresql
  database: database_test
  username: ManishKukreja
  password: unix11
  template: template0
  pool: 5
  timeout: 5000
  port: 5432
